# Generated by Django 5.2 on 2025-04-26 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='modality',
            options={'verbose_name': 'Modalidad', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='penaltytype',
            options={'verbose_name': 'Tipo de Penalización', 'verbose_name_plural': 'Tipos de Penalización'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='racecategory',
            options={'verbose_name': 'Categoría de Carrera', 'verbose_name_plural': 'Categorías de Carrera'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_age',
            field=models.PositiveSmallIntegerField(verbose_name='Edad máxima'),
        ),
        migrations.AlterField(
            model_name='category',
            name='min_age',
            field=models.PositiveSmallIntegerField(verbose_name='Edad mínima'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_end',
            field=models.DateTimeField(verbose_name='Fin de inscripciones'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(verbose_name='Inicio de inscripciones'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, verbose_name='Documentos requeridos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='required_vaccines',
            field=models.JSONField(blank=True, default=list, verbose_name='Vacunas requeridas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True, verbose_name='Reglamento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('registration_open', 'Inscripciones abiertas'), ('registration_closed', 'Inscripciones cerradas'), ('in_progress', 'En progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='penaltytype',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='penaltytype',
            name='is_disqualification',
            field=models.BooleanField(default=False, verbose_name='Es descalificación'),
        ),
        migrations.AlterField(
            model_name='penaltytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='penaltytype',
            name='time_penalty',
            field=models.DurationField(blank=True, null=True, verbose_name='Penalización de tiempo'),
        ),
        migrations.AlterField(
            model_name='race',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora real de inicio'),
        ),
        migrations.AlterField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.DecimalField(decimal_places=2, help_text='Distancia en kilómetros', max_digits=5, verbose_name='Distancia'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='race',
            name='interval_seconds',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Segundos entre intervalos'),
        ),
        migrations.AlterField(
            model_name='race',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, verbose_name='Máximo de participantes'),
        ),
        migrations.AlterField(
            model_name='race',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='events.modality', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='race',
            name='participants_per_interval',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Participantes por intervalo'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(verbose_name='Fecha de carrera'),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_time',
            field=models.TimeField(verbose_name='Hora de carrera'),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_type',
            field=models.CharField(choices=[('mass', 'Salida en masa'), ('waves', 'Salida por oleadas'), ('intervals', 'Salida por intervalos')], default='mass', max_length=10, verbose_name='Tipo de salida'),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_categories', to='events.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='0 significa ilimitado', verbose_name='Cupo'),
        ),
        migrations.AlterField(
            model_name='racecategory',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_categories', to='events.race', verbose_name='Carrera'),
        ),
    ]
