# Generated by Django 5.2 on 2025-04-22 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Perro', 'verbose_name_plural': 'Perros'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=100, verbose_name='Raza'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de microchip'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='participants.participant', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='veterinary_book_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de cartilla veterinaria'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='club',
            field=models.CharField(blank=True, max_length=100, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id_document',
            field=models.CharField(blank=True, help_text='DNI, pasaporte u otro documento de identidad', max_length=20, verbose_name='Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia/Estado'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
