# Generated by Django 5.2 on 2025-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_dog_options_alter_participant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='Número de participante'),
        ),
    ]
