# Generated by Django 5.2 on 2025-04-26 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_category_options_alter_modality_options_and_more'),
        ('participants', '0002_alter_dog_options_alter_participant_options_and_more'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='participantannotation',
            options={'verbose_name': 'Anotación de Participante', 'verbose_name_plural': 'Anotaciones de Participantes'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['race', 'bib_number'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('identity', 'Documento de Identidad'), ('veterinary_certificate', 'Certificado Veterinario'), ('vaccination_record', 'Registro de Vacunación'), ('insurance', 'Certificado de Seguro'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_analysis_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Resultado análisis IA'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_raw_text',
            field=models.TextField(blank=True, verbose_name='Texto extraído por OCR'),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Estado OCR'),
        ),
        migrations.AlterField(
            model_name='document',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.registration', verbose_name='Inscripción'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_annotations', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación en el recorrido donde ocurrió la infracción', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='penalty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='events.penaltytype', verbose_name='Tipo de penalización'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_annotations', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='registrations.registration', verbose_name='Inscripción'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='status',
            field=models.CharField(choices=[('recorded', 'Registrada'), ('confirmed', 'Confirmada'), ('dismissed', 'Desestimada')], default='recorded', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='participantannotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='ai_vaccine_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('ok', 'Correcto'), ('issue', 'Con incidencia'), ('error', 'Error/Requiere revisión')], default='pending', max_length=20, verbose_name='Estado de vacunas (IA)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='bib_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de dorsal'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Check-in realizado'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de check-in'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='participants.dog', verbose_name='Perro'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='kit_delivered',
            field=models.BooleanField(default=False, verbose_name='Kit entregado'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='kit_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de entrega de kit'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='participants.participant', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('refunded', 'Reembolsado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.race', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='race_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.racecategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado de inscripción'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vet_check_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado de revisión veterinaria'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vet_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de revisión veterinaria'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='vet_checker_details',
            field=models.TextField(blank=True, verbose_name='Detalles de revisión veterinaria'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='waiver_accepted',
            field=models.BooleanField(default=False, verbose_name='Descargo de responsabilidad aceptado'),
        ),
    ]
