# Generated by Django 5.2 on 2025-04-26 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0002_alter_dog_options_alter_participant_options_and_more'),
        ('registrations', '0002_alter_document_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinaryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En revisión'), ('approved', 'Aprobado'), ('conditional', 'Aprobado con condiciones'), ('rejected', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ritmo cardíaco (lpm)')),
                ('physical_condition', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy bueno'), (5, 'Excelente')], null=True, verbose_name='Condición física')),
                ('hydration_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Deficiente'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy bueno'), (5, 'Excelente')], null=True, verbose_name='Estado de hidratación')),
                ('has_injuries', models.BooleanField(default=False, verbose_name='Presenta heridas o lesiones')),
                ('injury_details', models.TextField(blank=True, verbose_name='Detalle de lesiones')),
                ('has_respiratory_issues', models.BooleanField(default=False, verbose_name='Problemas respiratorios')),
                ('respiratory_details', models.TextField(blank=True, verbose_name='Detalles respiratorios')),
                ('has_musculoskeletal_issues', models.BooleanField(default=False, verbose_name='Problemas musculoesqueléticos')),
                ('musculoskeletal_details', models.TextField(blank=True, verbose_name='Detalles musculoesqueléticos')),
                ('vaccines_verified', models.BooleanField(default=False, verbose_name='Vacunas verificadas')),
                ('vaccines_notes', models.TextField(blank=True, verbose_name='Notas sobre vacunas')),
                ('general_notes', models.TextField(blank=True, verbose_name='Notas generales')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_checks', to='participants.dog', verbose_name='Perro')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_check', to='registrations.registration', verbose_name='Inscripción')),
                ('veterinarian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_checks', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
            options={
                'verbose_name': 'Revisión Veterinaria',
                'verbose_name_plural': 'Revisiones Veterinarias',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='Nombre de la vacuna')),
                ('administration_date', models.DateField(verbose_name='Fecha de administración')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Número de lote')),
                ('verified', models.BooleanField(default=True, verbose_name='Verificada')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('veterinary_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='veterinary.veterinarycheck', verbose_name='Revisión veterinaria')),
            ],
            options={
                'verbose_name': 'Registro de Vacunación',
                'verbose_name_plural': 'Registros de Vacunación',
                'ordering': ['-administration_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requires_followup', models.BooleanField(default=False, verbose_name='Requiere seguimiento')),
                ('notify_staff', models.BooleanField(default=False, verbose_name='Notificar al staff')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('monitoring', 'En monitoreo'), ('resolved', 'Resuelta'), ('dismissed', 'Descartada')], default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('veterinary_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_alerts', to='veterinary.veterinarycheck', verbose_name='Revisión veterinaria')),
            ],
            options={
                'verbose_name': 'Alerta Médica',
                'verbose_name_plural': 'Alertas Médicas',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
